// 页面切换逻辑
document.getElementById('startButton').addEventListener('click', () => {
    document.getElementById('landingPage').classList.add('hidden');
    document.getElementById('mainContent').classList.remove('hidden');
});

// 答案数据
const answers = {
    1: "以更放松的态度去面对 \nFace it with a more relaxed attitude",
    2: "告诉别人这对你的意义 \nTell others what it means to you",
    3: "保持开放的心态 \nKeep an open mind",
    4: "这是制定计划的好时机 \nThis is a good time to make a plan",
    5: "这可能很困难 \nThis may be difficult",
    6: "但你会发现它的价值 \nBut you will find its value",
    7: "别怕改变 \nDon't be afraid of change",
    8: "这点麻烦是值得的 \nThis trouble is worth it",
    9: "你肯定会被支持的 \nYou will definitely be supported",
    10: "寻求更多的选择 \nSeek more options",
    11: "你不可能失败 \nYou can't fail",
    12: "你必须现在行动 \nYou must act now",
    13: "坚持就是胜利 \nPersistence leads to victory",
    14: "你不会失望 \nYou won't be disappointed",
    15: "遵从你的意愿 \nFollow your will",
    16: "花更多的时间来决定 \nSpend more time making a decision",
    17: "别忽视显而易见的东西 \nDon't ignore the obvious",
    18: "过段时间就不那么重要了 \nIt won't be that important after some time",
    19: "拭目以待 \nWait and see",
    20: "相信你最初的想法 \nTrust your original idea",
    21: "请不要抗拒 \nPlease don't resist",
    22: "这不重要 \nIt doesn't matter",
    23: "那一定很棒 \nThat must be great",
    24: "把它记下来 \nWrite it down",
    25: "不要迫于压力草率行事 \nDon't act hastily under pressure",
    26: "可能发生小意外 \nA small accident may occur",
    27: "研究并享受它 \nStudy and enjoy it",
    28: "这具有重要意义 \nThis is of great significance",
    29: "防止意外发生 \nPrevent accidents from happening",
    30: "不 \nNo",
    31: "一切将取决于你的选择 \nEverything will depend on your choice",
    32: "转移注意力 \nDivert attention",
    33: "离开你需要其他人的帮助 \nYou need help from others to leave",
    34: "这有些特别 \nThis is a bit special",
    35: "不要犹豫 \nDon't hesitate",
    36: "先完成其他事 \nFinish other things first",
    37: "给自己一点时间 \nGive yourself a little time",
    38: "现在你就能 \nNow you can",
    39: "那不值得纠结 \nThat's not worth worrying about",
    40: "那将影响别人对你的看法 \nThat will affect how others see you",
    41: "照别人说的去做 \nDo as others say",
    42: "转移你的注意力 \nDivert your attention",
    43: "你会失望的 \nYou will be disappointed",
    44: "现在不是下定论的时候，保持关注，答案会逐渐清晰 \nIt's better to focus on your work; the situation is unclear",
    45: "结果可能令人吃惊 \nThe result may be surprising",
    46: "有决心就能成功 \nDetermination leads to success",
    47: "你的行动会使一切得到改善 \nYour actions will improve everything",
    48: "做一次改变 \nMake a change",
    49: "照别人告诉你的去做 \nDo as others tell you",
    50: "​把大目标忘掉，只专注于接下来的24小时 \nThere's no guarantee; the answer may appear in another form",
    51: "毋庸置疑 \nUndoubtedly",
    52: "这样做会使事情变得有趣 \nDoing this will make things interesting",
    53: "这是肯定的 \nThis is certain",
    54: "有可能会伤害到他人 \nIt may hurt others",
    55: "那只会浪费钱 \nThat will only waste money",
    56: "采取冒险的态度 \nAdopt an adventurous attitude",
    57: "最好等待 \nIt's better to wait",
    58: "超出了你的控制 \nBeyond your control",
    59: "可能会惹上麻烦 \nMay get into trouble",
    60: "你需要采取主动 \nYou need to take the initiative",
    61: "似乎没问题 \nIt seems okay",
    62: "肯定 \nCertainly",
    63: "不要在意 \nDon't care",
    64: "尽早做好它 \nDo it as soon as possible",
    65: "你终会发现你想要知道的一切 \nYou will eventually find out everything you want to know",
    66: "除非你独自一人做 \nUnless you do it alone",
    67: "是，但不要强求 \nYes, but don't force it",
    68: "你需要去适应 \nYou need to adapt",
    69: "明天再试试 \nTry again tomorrow",
    70: "这会带来好运 \nThis will bring good luck",
    71: "你需要考虑其他方法 \nYou need to consider other methods",
    72: "习惯于接受改变 \nGet used to accepting change",
    73: "别浪费时间了 \nDon't waste time",
    74: "是的 \nYes",
    75: "这还不确定 \nThis is still uncertain",
    76: "谨慎处理 \nHandle with caution",
    77: "全力以赴 \nGo all out",
    78: "重新考虑你的做法 \nReconsider your approach",
    79: "问问你的母亲吧 \nAsk your mother",
    80: "不要独自一人去做 \nDon't do it alone",
    81: "或许当你长大些就知道了 \nMaybe you'll understand when you grow up",
    82: "不要担忧 \nDon't worry",
    83: "你会为自己所做的感到高兴的 \nYou will be happy with what you did",
    84: "发挥你的想象力 \nUse your imagination",
    85: "献出你的一切 \nGive your all",
    86: "尽可能顺从你的意愿 \nComply with your will as much as possible",
    87: "绝不问问你的母亲吧 \nNever ask your mother",
    88: "当然 \nOf course",
    89: "先做好自己应做的事 \nDo what you should do first",
    90: "不要怀疑 \nDon't doubt",
    91: "是时候重新打算了 \nIt's time to make new plans",
    92: "不要忽略显而易见的东西 \nDon't ignore the obvious",
    93: "跟随你的直觉 \nSave your energy",
    94: "此时不宜 \nNot suitable at this time",
    95: "莫等待 \nDon't wait",
    96: "灵活应对 \nRespond flexibly",
    97: "似乎已成事实 \nIt seems to be a fact",
    98: "看开一点 \nTake it easy",
    99: "问问你的异性同事 \nAsk your opposite-sex colleague",
    100: "柳暗花明又一村 \nWhen one path closes, another opens",
    101: "你会后悔的 \nYou will regret it",
    102: "避免第一个解决办法 \nAvoid the first solution",
    103: "随他去吧 \nLet it be",
    104: "不要包成见 \nDon't hold prejudices",
    105: "你必须现在就行动 \nYou must act now",
    106: "那可能很难，但值得 \nIt may be difficult, but it's worth it",
    107: "付出就会有回报 \nPay will be rewarded",
    108: "对意外要有思想准备 \nBe prepared for the unexpected",
    109: "更细心的去倾听，你就会知道 \nListen more carefully, and you will know",
    110: "且行且思 \nThink while walking",
    111: "耐心是此刻的钥匙 \nUnable to change in any way",
    112: "这些是你不会忘记的事情 \nThese are things you won't forget",
    113: "履行你的义务 \nFulfill your obligations",
    114: "快刀斩乱麻 \nCut the Gordian knot",
    115: "别在这上面下赌注 \nDon't bet on this",
    116: "也许 \nMaybe",
    117: "专注于你的家庭生活 \nFocus on your family life",
    118: "绝对不等待 \nAbsolutely don't wait",
    119: "别犯傻了 \nDon't be silly",
    120: "可能 \nPossible",
    121: "表示怀疑 \nExpress doubt",
    122: "意义非凡 \nOf extraordinary significance",
    123: "那可能非同寻常 \nThat may be unusual",
    124: "不可能失败 \nImpossible to fail",
    125: "你需要了解更多情况 \nYou need to know more",
    126: "很快会有变化 \nChanges will come soon",
    127: "顺其自然 \nLet nature take its course",
    128: "问问你最好的朋友 \nAsk your best friend",
    129: "这事不要再自找麻烦 \nDon't trouble yourself with this matter anymore",
    130: "晚一点处理 \nDeal with it later",
    131: "尝试一种更可能的解决方案 \nTry a more likely solution",
    132: "先做好其他事 \nFinish other things first",
    133: "不要陷入消极情绪之中 \nDon't fall into negative emotions",
    134: "相信你的直觉 \nTrust your intuition",
    135: "这不是终点，只是一个转弯 \nAdopt the teacher's advice",
    136: "学习等待，答案自会浮现 \nThe situation is unclear",
    137: "是时候做些打算了 \nIt's time to make some plans",
    138: "你不得不妥协 \nYou have to compromise",
    139: "列出否定的理由 \nList the reasons for denial",
    140: "这并不重要 \nThis is not important",
    141: "要有耐心 \nBe patient",
    142: "寻求更多选择 \nSeek more options",
    143: "一笑置之 \nLaugh it off",
    144: "继续 \nContinue",
    145: "你必须随机应变 \nYou must adapt to circumstances",
    146: "别忘记享受乐趣 \nDon't forget to enjoy the fun",
    147: "关注过程，而非结果 \nThat's a waste of money",
    148: "重要的优先 \nPrioritize the important",
    149: "事情会朝目标发展 \nThings will move towards the goal",
    150: "为了做出最好的决定 \nTo make the best decision",
    151: "务必保持冷静 \nBe sure to stay calm",
    152: "尝试一个更没有把握的方法 \nTry a more uncertain method",
    153: "清楚你自身的短板 \nBe clear about your own shortcomings",
    154: "那可能已成事实 \nThat may be a fact",
    155: "先做重要的事 \nDo important things first",
    156: "投硬币来做决定 \nFlip a coin to make a decision",
    157: "这不可能失败 \nThis can't fail",
    158: "这也取决于另一种情况 \nThis also depends on another situation",
    159: "不要强求不可能的事 \nDon't force the impossible",
    160: "你最终能如愿 \nYou will eventually get what you want",
    161: "可行 \nFeasible",
    162: "现在你比以往任何时候都看得更清楚 \nNow you see more clearly than ever before",
    163: "只需要说声谢谢 \nJust need to say thank you",
    164: "或许等你再年长些就明白了 \nMaybe you'll understand when you're older",
    165: "这将轰动一时 \nThis will cause a sensation",
    166: "放手一搏 \nTake a bold gamble",
    167: "答案可能会以另一种形式出现 \nThe answer may appear in another form",
    168: "了解的越透彻，你的目标便会越明确 \nThe more thoroughly you understand, the clearer your goal will be",
    169: "需要做更多的努力 \nNeed to make more efforts",
    170: "等待一个更好的时机 \nWait for a better time",
    171: "数到十再试一次 \nCount to ten and try again",
    172: "你不得不放弃 \nYou have to give up",
    173: "也许很难，但值得 \nMaybe it's hard, but it's worth it",
    174: "很快就能决定 \nWill be able to decide soon",
    175: "十分肯定 \nVery certain",
    176: "你必须放弃 \nYou must give up",
    177: "遵从规则 \nFollow the rules",
    178: "相关问题可能会出现 \nRelated problems may arise",
    179: "事情将遂你心意 \nThings will go as you wish",
    180: "赌一把 \nTake a bet",
    181: "以后再处理 \nDeal with it later",
    182: "结果将是乐观的 \nThe result will be optimistic",
    183: "把握契机，灵活应对 \nSeize the opportunity and respond flexibly",
    184: "注意细节 \nPay attention to details",
    185: "你的行动会使一切变好 \nYour actions will make everything better",
    186: "清除你自身的短板 \nEliminate your own shortcomings",
    187: "这是不可取的 \nThis is not advisable",
    188: "将需要大量的努力 \nWill require a lot of effort",
    189: "不要勉强自己 \nDon't force yourself",
    190: "是时候做打算了 \nIt's time to make plans",
    191: "享受这次体验 \nEnjoy this experience",
    192: "要付出坚持不懈的努力 \nNeed to make persistent efforts",
    193: "那仍旧无法预测 \nThat is still unpredictable",
    194: "结果是乐观的 \nThe result is optimistic",
    195: "多花点时间来做决定 \nSpend more time making a decision",
    196: "只做这一次 \nOnly do this once",
    197: "做些改变 \nMake some changes",
    198: "行得通 \nWorks",
    199: "相信你最开始的想法 \nTrust your initial idea",
    200: "先主后次 \nPrioritize the main over the secondary",
    201: "你需要适应 \nYou need to adapt",
    202: "这会让你付出代价 \nThis will cost you",
    203: "尽早行动 \nAct as soon as possible",
    204: "可能会伤害到别人 \nMay hurt others",
    205: "你比以往任何时候都更清楚 \nYou see more clearly than ever before",
    206: "极可能发生变故 \nChanges are very likely to occur",
    207: "毫无疑问 \nNo doubt",
    208: "本页后第一个答案 \nThe first answer after this page",
    209: "带着好奇去探索 \nExplore with curiosity",
    210: "列出这样做的理由 \nList the reasons for doing this",
    211: "马上停下来 \nStop right away",
    212: "不是很确定 \nNot very sure",
    213: "不用担心 \nDon't worry",
    214: "首先做好自己的事 \nFirst do your own things well",
    215: "情况很快就会有变化 \nThe situation will change soon",
    216: "你需要其他人的帮助 \nYou need help from others",
    217: "不要告诉别人 \nDon't tell others",
    218: "现在你就行 \nYou can do it now",
    219: "仍然无法预测 \nStill unpredictable",
    220: "列出理由 \nList the reasons",
    221: "压力之下不要草率行事 \nDon't act hastily under pressure",
    222: "是 \nYes",
    223: "你需要主动一些 \nYou need to be more proactive",
    224: "不要等待 \nDon't wait",
    225: "是你必须马上行动 \nYou must act immediately",
    226: "不要妄下赌注 \nDon't place bets recklessly",
    227: "接受改变 \nAccept change",
    228: "可能已经无法改变 \nMay have been unchangeable",
    229: "一些援助能确保你成功 \nSome assistance can ensure your success",
    230: "你肯定会获得支持 \nYou will definitely get support",
    231: "仅做一次 \nOnly do it once",
    232: "听从朋友的建议 \nFollow a friend's advice",
    233: "如你所愿 \nAs you wish",
    234: "当局者迷 \nThe person involved is confused",
    235: "无论你怎么做，结果依旧 \nNo matter what you do, the result remains the same",
    236: "你能以任何方式改善现状 \nYou can improve the current situation in any way",
    237: "为了做出最好的选择，请保持冷静 \nTo make the best choice, please stay calm",
    238: "你会为此感到高兴 \nYou will be happy about this",
    239: "放弃之前的想法 \nGive up the previous idea",
    240: "顺从你的意愿 \nComply with your will",
    241: "你不会忘记这些 \nYou won't forget these",
    242: "不要在乎 \nDon't care",
    243: "一些援助有利于你成功 \nSome assistance is beneficial to your success",
    244: "谨慎对待 \nTreat with caution",
    245: "抛硬币来做决定吧 \nFlip a coin to make a decision",
    246: "放弃你现在的想法 \nGive up your current idea",
    247: "有理由保持乐观 \nThere is reason to be optimistic",
    248: "你会发现自己难以妥协 \nYou will find it hard to compromise",
    249: "是时候做新打算了 \nIt's time to make new plans",
    250: "改变不会很快发生 \nChange won't happen soon",
    251: "仔细的聆听，然后你就会知道 \nListen carefully, and then you will know",
    252: "耐心点 \nBe patient",
    253: "果断放弃 \nGive up decisively",
    254: "随心而行 \nFollow your heart",
    255: "最好把心思放在工作上 \nIt's better to focus on work",
    256: "要做就做好，否则就不要去做 \nDo it well if you do it, otherwise don't do it",
    257: "深表怀疑 \nDeeply doubtful",
    258: "最好的解决方法还不明朗 \nThe best solution is still unclear",
    259: "运用你的想象力 \nUse your imagination",
    260: "已超出你的控制 \nBeyond your control",
    261: "你已然发现自己无法妥协 \nYou have already found it hard to compromise",
    262: "看看会发生什么 \nSee what happens",
    263: "你需要更多信息 \nYou need more information",
    264: "数到五，再问一次 \nCount to five and ask again",
    265: "开阔视野 \nBroaden your horizons",
    266: "看得更清楚些 \nSee more clearly",
    267: "结果可能会令人震惊 \nThe result may be shocking",
    268: "不要浪费你的精力 \nDon't waste your energy",
    269: "管他呢 \nWho cares",
    270: "那将引起一些纷争 \nThat will cause some disputes",
    271: "相关问题可能会浮出水面 \nRelated issues may surface",
    272: "先主后次 \nPrioritize the main over the secondary",
    273: "重新考虑一下你的方法 \nReconsider your method",
    274: "你可能遭遇反对 \nYou may encounter opposition",
    275: "你能否不要抗拒 \nCan you not resist",
    276: "放弃之前的打算 \nGive up previous plans",
    277: "有障碍需要克服 \nThere are obstacles to overcome",
    278: "做出改变 \nMake a change",
    279: "无法保证 \nNo guarantee",
    280: "算了吧 \nForget it",
    281: "把这看作一次时机 \nTreat this as an opportunity",
    282: "别再犹豫 \nDon't hesitate anymore",
    283: "保守你的秘密 \nKeep your secret",
    284: "遵从其他人的建议 \nFollow others' advice",
    285: "改变将不会很快发生 \nChange won't happen soon",
    286: "值得付出努力 \nWorth the effort",
    287: "负起责任来 \nTake responsibility",
    288: "你终会搞清楚你想要的一切 \nYou will eventually figure out everything you want",
    289: "如果做就做好，否则就不要做 \nDo it well if you do it, otherwise don't do it",
    290: "不值得一争 \nNot worth arguing about",
    291: "遵守规定 \nAbide by the rules",
    292: "管它呢 \nWho cares",
    293: "问问你的父亲 \nAsk your father",
    294: "向别人倾诉 \nTalk to others",
    295: "看起来还行 \nLooks okay",
    296: "等待一个更好的提议 \nWait for a better offer",
    297: "绝对不会 \nAbsolutely not",
    298: "你有可能会遭遇反对 \nYou may encounter opposition",
    299: "这会是一件乐事 \nThis will be a pleasure",
    300: "告诉某人那对你意味着什么 \nTell someone what it means to you",
    301: "这会影响别人对你的看法 \nThis will affect how others see you",
    302: "一切都取决于你的选择 \nEverything depends on your choice",
    303: "把这看作一个时机 \nTreat this as an opportunity",
    304: "不要陷入坏情绪 \nDon't fall into a bad mood",
    305: "你一定得这么做 \nYou must do this",
    306: "享受这个过程 \nEnjoy the process",
    307: "不识庐山真面目，只缘身在此山中 \nYou can't see the true face of Mount Lu because you are in the mountain",
    308: "等待 \nWait",
    309: "最好解决办法还不明朗 \nThe best solution is still unclear",
    310: "问问你的父亲吧 \nAsk your father",
    311: "你不得不放弃其他一些东西 \nYou have to give up some other things",
    312: "你不会失望的 \nYou won't be disappointed",
    313: "是时候走了 \nIt's time to go",
    314: "先做好自己的事 \nDo your own things first",
    315: "享受这种经历 \nEnjoy this experience",
    316: "尽早去做 \nDo it as soon as possible",
    317: "你最好等一等 \nYou'd better wait",
    318: "说出来吧 \nSpeak up",
    319: "欣然接受 \nAccept gladly",
    320: "听从其他人的意见 \nFollow others' opinions",
    321: "别这么荒唐 \nDon't be so absurd",
    322: "或许吧 \nMaybe",
    323: "决不 \nNever",
    324: "自强不息 \nStrive for self-improvement",
    325: "起始维艰 \nThe beginning is difficult",
    326: "动静有时 \nThere is a time for movement and stillness",
    327: "晦而转明 \nFrom darkness to light",
    328: "异中求同 \nSeek common ground among differences",
    329: "所遇皆甜 \nEverything encountered is sweet",
    330: "困境求通 \nSeek a way out in difficulties",
    331: "临危不乱 \nStay calm in a crisis",
    332: "需要耐心 \nNeed patience",
    333: "换位思考 \nPut yourself in others' shoes",
    334: "厚德载物 \nHave a virtuous heart to bear things",
    335: "守正待机 \nUphold integrity and wait for opportunities",
    336: "慎争戒讼 \nBe cautious in disputes and avoid lawsuits",
    337: "行险而顺 \nTake risks but go smoothly",
    338: "蓄养待进 \nCultivate and wait for progress",
    339: "脚踏实地 \nBe down-to-earth",
    340: "因时而变 \nChange with the times",
    341: "如梦初醒 \nWake up as if from a dream",
    342: "上下和同 \nUnity between superiors and subordinates",
    343: "顺天依时 \nComply with heaven and follow the times",
    344: "峰回路转 \nThe path winds and turns",
    345: "祸兮福之所倚，福兮祸之所伏 \nMisfortune is where blessing lies, and blessing is where misfortune hides",
    346: "顺势而止 \nStop with the trend",
    347: "寓动于顺 \nContain movement in smoothness",
    348: "无妄而得 \nGain without delusion",
    349: "止而不止 \nStop yet not stop",
    350: "知足天地宽，贪得宇宙隘 \nContentment makes the world wide, greed makes the universe narrow",
    351: "恒心有成 \nPerseverance leads to success",
    352: "决而能和 \nDecide and be harmonious",
    353: "稳重图变 \nBe steady and seek change",
    354: "危机并存 \nCrisis and opportunity coexist",
    355: "日中则斜 \nThe sun inclines after midday",
    356: "使口不如自走，求人不如求己 \nIt's better to go by yourself than to ask others to speak for you; it's better to rely on yourself than others",
    357: "依义顺时 \nComply with justice and the times",
    358: "行动有度 \nAct with moderation",
    359: "岁月静好 \nThe years are peaceful and quiet",
    360: "不弃功于寸阴 \nDon't waste an inch of time",
    361: "春光不自留，莫怪东风恶 \nSpring won't stay by itself, don't blame the east wind for being fierce",
    362: "欢天喜地 \nBe overjoyed",
    363: "细水长流 \nA small stream flows long",
    364: "慎终如始 \nBe as cautious at the end as at the beginning",
    365: "独脚难行，孤掌难鸣 \nA single foot can't walk, a single palm can't make a sound",
    366: "去时终须去，再三留不住 \nWhat must leave will leave eventually, no matter how hard you try to keep it",
    367: "瓜熟蒂落，水到渠成 \nWhen the melon is ripe, it falls from the vine; when the water flows, a channel is formed",
    368: "捕风捉影 \nChase the wind and catch shadows (chase illusions)",
    369: "得失参半 \nGains and losses are half and half",
    370: "想法太多，选择太少 \nToo many ideas, too few choices",
    371: "是非终日有，不得自然无 \nRight and wrong exist every day; they will disappear naturally if not pursued",
    372: "相信自己 \nBelieve in yourself",
    373: "寻寻觅觅 \nSearching everywhere",
    374: "信心满满 \nFull of confidence",
    375: "自知之明 \nSelf-awareness",
    376: "和光同尘 \nBlend with the light and dust (be modest and low-key)",
    377: "人有所愿，天必佑之 \nIf a person has a wish, heaven will bless it",
    378: "释然面对 \nFace it with relief",
    379: "知止不殆 \nKnow when to stop to avoid danger",
    380: "缓而图之 \nTake it slowly and plan for it",
    381: "出人意料 \nBeyond expectation",
    382: "理性待之 \nTreat it rationally",
    383: "心安理得 \nFeel at ease and justified",
    384: "回头是岸 \nTurn back and you'll be on the shore (repent and reform)",
    385: "过而能改 \nRealize mistakes and correct them",
    386: "责人不如责己 \nIt's better to blame yourself than others",
    387: "时机未到 \nThe time is not right",
    388: "知足常乐 \nContentment brings constant happiness",
    389: "取之有道 \nObtain things in a proper way",
    390: "直道而行 \nWalk on the straight path",
    391: "海纳百川 \nThe sea accepts all rivers (be broad-minded)",
    392: "久旱逢甘霖 \nLong drought meets timely rain",
    393: "有理不在高声 \nReason doesn't lie in loudness",
    394: "百事大吉前景春 \nEverything goes well and the future is promising",
    395: "临渊羡鱼，不如退而结网 \nIt's better to retreat and weave a net than to envy fish by the abyss",
    396: "拈花微笑，吉星高照 \nTwist a flower and smile, with auspicious stars shining brightly",
    397: "合理可作，小利莫争 \nDo what is reasonable, don't argue over small gains",
    398: "下一页才是你的答案 \nThe next page is your answer",
    399: "好雨知时节，当春乃发生 \nGood rain knows its time, falling when spring arrives",
    400: "纸上得来终觉浅，绝知此事要躬行 \nKnowledge from books is always superficial; you must practice to truly understand",
    401: "洞房花烛夜，金榜题名时 \nThe night of wedding candles, the time of passing the imperial examination (the happiest moments in life)",
    402: "大道如青天，我独不得出 \nThe great road is like the blue sky, but I alone can't go out",
    403: "往者不可谏，来者犹可追 \nThe past can't be remedied, but the future can still be pursued",
    404: "当局者迷旁观者清 \nThe person involved is confused, while the onlooker sees clearly",
    405: "埋头苦干 \nWork hard with one's head down",
    406: "山不过来，我就过去 \nIf the mountain doesn't come to me, I'll go to the mountain",
    407: "柳暗花明 \nDark willows and bright flowers (a new prospect after difficulty)",
    408: "等待，下暗劲 \nWait and work hard secretly",
    409: "另谋出路 \nSeek another way out",
    410: "盛年不重来，一日难再晨 \nThe prime of life never comes again; a day never has two mornings",
    411: "和解为上 \nReconciliation is the best",
    412: "积水成渊 \nAccumulated water forms a deep pool",
    413: "回归本位 \nReturn to one's original position",
    414: "不乱方寸 \nDon't lose one's composure",
    415: "勇往直前 \nMarch forward courageously",
    416: "随遇而安 \nAdapt to circumstances and be content",
    417: "过犹不及 \nGoing too far is as bad as not going far enough",
    418: "返璞归真 \nReturn to simplicity and authenticity",
    419: "按兵不动 \nHold troops and not move (wait and see)",
    420: "野火烧不尽，春风吹又生 \nWildfires can't burn it out; it grows again with the spring breeze",
    421: "志在必得 \nDetermined to get it",
    422: "欲穷千里目，更上一层楼 \nTo see a thousand miles, climb one more storey",
    423: "修身自省 \nCultivate oneself and reflect on oneself",
    424: "失之东隅，收之桑榆 \nLose at dawn, gain at dusk (lose in one place, gain in another)",
    425: "既知莫望，不知莫向 \nIf you know it, don't hope for more; if you don't know it, don't move towards it",
    426: "言之者无罪，闻之者是以戒 \nThe speaker is innocent; the listener should take warning",
    427: "中行无咎 \nWalking in the middle way is blameless",
    428: "事半功倍 \nGet twice the result with half the effort",
    429: "处变不惊 \nStay calm in the face of changes",
    430: "莫道桑榆晚，为霞尚满天 \nDon't say the sunset is late; the rosy clouds still fill the sky",
    431: "尽力而为 \nDo one's best",
    432: "精诚所至 \nSincerity reaches (sincerity can move people)",
    433: "乘风破浪 \nRide the wind and break the waves",
    434: "一念既出，万山难阻 \nOnce an idea is put forward, ten thousand mountains can't stop it",
    435: "舍鱼而取熊掌者也 \nGive up fish and take bear's paw (choose the more valuable one)",
    436: "望眼欲穿 \nEyes are worn out with longing",
    437: "梨花一枝春带雨 \nA branch of pear blossoms with rain in spring (describes beauty with tenderness)",
    438: "善恶随人作，祸福自己招 \nGood and evil are done by people; fortune and misfortune are brought by oneself",
    439: "化繁为简 \nSimplify complexity",
    440: "坚守正道，终有回报 \nAdhere to the right path, and there will be rewards eventually",
    441: "金石为开 \nSincerity can open gold and stone (sincerity can overcome all difficulties)",
    442: "不迁怒，不贰过 \nDon't vent anger on others, don't make the same mistake twice",
    443: "有容乃大 \nTolerance leads to greatness",
    444: "晴带雨伞，饱带饥粮 \nTake an umbrella on a sunny day, take food when full (prepare for a rainy day)",
    445: "突破自我，迎接新生 \nBreak through oneself and embrace a new life",
    446: "少则得，多则惑 \nLess leads to gain, more leads to confusion",
    447: "洗心克欲 \nPurify the mind and restrain desires",
    448: "不居功，功自言 \nDon't claim credit; credit speaks for itself",
    449: "不愁无路，就怕不做 \nDon't worry about no way out; the fear is not doing it",
    450: "成人之美 \nHelp others achieve their ideals",
    451: "和而不同 \nBe harmonious but not identical",
    452: "蒸蒸日上 \nProsper day by day",
    453: "缓步当车，无祸当福 \nWalk slowly as if riding a cart; no disaster is like a blessing",
    454: "保持冷静，理智思考 \nStay calm and think rationally",
    455: " 求仁得仁 \nSeek benevolence and get benevolence",
    456: "工欲善其事必先利其器 \nA craftsman who wants to do his work well must first sharpen his tools",
    457: "行到水穷处，坐看云起时 \nWhen you reach the end of the water, sit and watch the clouds rise",
    458: "迎刃而解 \nSolve a problem with ease (like a knife cutting through butter)",
    459: "落红不是无情物，化作春泥更护花 \nFallen flowers are not heartless; they turn into spring mud to nourish flowers",
    460: "如鱼得水 \nLike a fish in water (very comfortable and suitable)",
    461: "自得其乐 \nEnjoy one's own company and find joy in it",
    462: "选择听从你的内心 \nChoose to listen to your heart",
    463: "忍耐任由风雨过 \nEndure and let the storm pass",
    464: "守得云开见月明 \nAfter the clouds disperse, the moon will shine",
    465: "若无闲事心头挂便是人间好时节 \nIf there's nothing weighing on your mind, it's the best time of life",
    466: "别依靠不能依靠的人 \nDon't rely on those who can't be relied upon",
    467: "何不把苦当磨练 \nWhy not take hardship as training",
    468: "细节决定成败 \nDetails determine success or failure",
    469: "态度决定一切 \nAttitude determines everything",
    470: "加把劲 \nPut in more effort",
    471: "你想得太多了 \nYou're overthinking it",
    472: "专心点 \nConcentrate",
    473: "你自己信吗 \nDo you even believe yourself",
    474: "理解你自己最重要 \nUnderstanding yourself is the most important",
    475: "不要着急 \nDon't be in a hurry",
    476: "不要怕麻烦 \nDon't be afraid of trouble",
    477: "积极面对 \nFace it positively",
    478: "有点担心 \nA little worried",
    479: "需要男性好友的意见 \nNeed advice from a male friend",
    480: "需要女性好友的意见 \nNeed advice from a female friend",
    481: "问问父母，他们走过的桥多 \nAsk your parents; they have more life experience",
    482: "霸王硬上弓 \nForce something to happen (act arbitrarily)",
    483: "软磨硬泡 \nPester persistently (softly and stubbornly)",
    484: "只要功夫深，铁杵磨成针 \nAs long as you work hard, an iron pestle can be ground into a needle",
    485: "现在不做，更待何时 \nIf not now, when",
    486: "值得一试 \nWorth a try",
    487: "保持冷静 \nStay calm",
    488: "学会拒绝 \nLearn to say no",
    489: "别自欺欺人 \nDon't deceive yourself",
    490: "量力而行 \nDo what you can according to your ability",
    491: "别钻牛角尖 \nDon't get stuck in a dead end",
    492: "换个角度想想 \nThink from another angle",
    493: "这不是你的责任 \nThis is not your responsibility",
    494: "接受不完美 \nAccept imperfection",
    495: "先睡一觉再说 \nSleep on it first",
    496: "需要更多信息 \nNeed more information",
    497: "答案在镜子里 \nThe answer is in the mirror",
    498: "放下执念 \nLet go of obsessions",
    499: "机会在敲门 \nOpportunity is knocking",
    500: "别把运气当实力 \nDon't mistake luck for ability",
    501: "沉默是金 \nSilence is gold",
    502: "三思而后行 \nThink twice before acting",
    503: "别为小事纠结 \nDon't get tangled in trivial matters",
    504: "相信直觉 \nTrust your intuition",
    505: "学会等待 \nLearn to wait",
    506: "及时止损 \nStop losses in time",
    507: "别怕孤独 \nDon't be afraid of loneliness",
    508: "化敌为友 \nTurn enemies into friends",
    509: "承认错误 \nAdmit mistakes",
    510: "别比较 \nDon't compare",
    511: "珍惜当下 \nCherish the present",
    512: "需要专业帮助 \nNeed professional help",
    513: "别过度承诺 \nDon't overcommit",
    514: "给自己留退路 \nLeave a way out for yourself",
    515: "别贴标签 \nDon't label people or things",
    516: "学会分享 \nLearn to share",
    517: "别怕说不 \nDon't be afraid to say no",
    518: "警惕甜言蜜语 \nBe alert to sweet words",
    519: "别找借口 \nDon't make excuses",
    520: "承认恐惧 \nAdmit fear",
    521: "别过度分析 \nDon't overanalyze",
    522: "接受差异 \nAccept differences",
    523: "别追求绝对公平 \nDon't pursue absolute fairness",
    524: "保持幽默感 \nKeep a sense of humor",
    525: "别重复错误 \nDon't repeat mistakes",
    526: "学会独处 \nLearn to be alone",
    527: "别为过去后悔 \nDon't regret the past",
    528: "控制情绪 \nControl emotions",
    529: "别传播负能量 \nDon't spread negative energy",
    530: "学会倾听 \nLearn to listen",
    531: "一天一天一天 \nDay by day by day",
    532: "别急于下结论 \nDon't jump to conclusions",
    533: "接受批评 \nAccept criticism",
    534: "别贪心 \nDon't be greedy",
    535: "保持好奇心 \nKeep curiosity",
    536: "别怕提问 \nDon't be afraid to ask questions",
    537: "承认无知 \nAdmit ignorance",
    538: "别迷信权威 \nDon't blindly believe in authority",
    539: "保持平衡 \nMaintain balance",
    540: "别逃避现实 \nDon't escape from reality",
    541: "别怕冲突 \nDon't be afraid of conflict",
    542: "接受不确定 \nAccept uncertainty",
    543: "别拖延 \nDon't procrastinate",
    544: "保持简单 \nKeep it simple",
    545: "别过度依赖 \nDon't over-rely",
    546: "承认弱点 \nAdmit weaknesses",
    547: "别怕被拒绝 \nDon't be afraid of rejection",
    548: "保持开放心态 \nKeep an open mind",
    549: "别固守己见 \nDon't cling to your own opinions",
    550: "接受帮助 \nAccept help",
    551: "别怕尝试 \nDon't be afraid to try",
    552: "保持耐心 \nBe patient",
    553: "别怕失败 \nDon't be afraid of failure",
    554: "承认需求 \nAdmit needs",
    555: "别怕不同 \nDon't be afraid of being different",
    556: "保持真诚 \nBe sincere",
    557: "别怕质疑 \nDon't be afraid to question",
    558: "接受成长 \nAccept growth",
    559: "别怕冒险 \nDon't be afraid to take risks",
    560: "保持谦逊 \nBe humble",
    561: "别怕改变主意 \nDon't be afraid to change your mind",
    562: "接受挑战 \nAccept challenges",
    563: "别怕说 \"我不知道\"\nDon't be afraid to say \"I don't know\"",
    564: "保持灵活性 \nMaintain flexibility",
    565: "别怕被误解 \nDon't be afraid of being misunderstood",
    566: "接受复杂性 \nAccept complexity",
    567: "别怕做决定 \nDon't be afraid to make decisions",
    568: "保持希望 \nKeep hope",
    569: "别怕放手 \nDon't be afraid to let go",
    570: "接受简单 \nAccept simplicity",
    571: "别怕复杂 \nDon't be afraid of complexity",
    572: "保持专注 \nStay focused",
    573: "别怕偏离计划 \nDon't be afraid to deviate from the plan",
    574: "这可能会让你付出代价 \nThis may cost you",
    575: "不能保证 \nNo guarantee",
    576: "这样做会使事情变得有趣 \nDoing this will make things interesting",
    577: "全身心投入将赢得好结果 \nWholehearted dedication will win good results",
    578: "那超出了你的控制 \nThat's beyond your control",
    579: "你终会发现你想知道的一切 \nYou will eventually find out everything you want to know",
    580: "除非你独自一人 \nUnless you are alone",
    581: "明天再来试试 \nTry again tomorrow",
    582: "在习惯中接受一些改变 \nAccept some changes in habits",
    583: "要知道选择太多和太少一样很难 \nKnow that too many choices are as difficult as too few",
    584: "花更多时间来决定 \nSpend more time deciding",
    585: "随它去吧 \nLet it be",
    586: "防备意外发生 \nPrepare for unexpected events",
    587: "一切将依赖于你的选择 \nEverything will depend on your choice",
    588: "离开 \nLeave",
    589: "本页后第四个答案 \nThe fourth answer after this page",
    590: "最好关注你的工作 \nIt's better to focus on your work",
    591: "形势尚不明朗 \nThe situation is unclear",
    592: "不要抱成见 \nDon't hold prejudices",
    593: "更细心地去倾听，你就会知道 \nListen more carefully and you will know",
    594: "你有能力以任何方式改善 \nYou have the ability to improve in any way",
    595: "这是你不会忘记的事物 \nThis is something you won't forget",
    596: "也许吧 \nMaybe",
    597: "绝对不 \nAbsolutely not",
    598: "可能吧 \nProbably",
    599: "你需要了解更多 \nYou need to know more",
    600: "情况很快会有变化 \nThe situation will change soon",
    601: "这时不要再自找麻烦 \nDon't ask for trouble at this time",
    602: "先做重要的事儿 \nDo important things first",
    603: "投硬币来做决定吧 \nFlip a coin to make a decision",
    604: "答案就在你家窗外 \nThe answer is outside your window",
    605: "现在你比以往任何时候都清楚 \nNow you are clearer than ever before",
    606: "只需说声 \"谢谢\"\nJust say \"thank you\"",
    607: "或许，等你再年长些就明白了 \nMaybe you will understand when you are older",
    608: "更细心去了解，你就知道该怎么做了 \nUnderstand more carefully and you will know what to do",
    609: "等待一个更好的机会 \nWait for a better opportunity",
    610: "数到5 再试一次 \nCount to 5 and try again",
    611: "也许会很难，但值得 \nIt may be difficult, but it's worth it",
    612: "很快就能解决 \nIt will be solved soon",
    613: "十分确定 \nVery certain",
    614: "如果你独自一人就不要 \nDon't do it if you are alone",
    615: "或许，当你长大些就知道了 \nMaybe you will know when you grow up",
    616: "无须担忧 \nNo need to worry",
    617: "不要忽略显而易见的 \nDon't ignore the obvious",
    618: "合作将是关键 \nCooperation will be the key",
    619: "你可能不得不放弃其他的东西 \nYou may have to give up other things",
    620: "遵守规则 \nAbide by the rules",
    621: "答案就在公园里 \nThe answer is in the park",
    622: "清除你自身的障碍 \nClear your own obstacles",
    623: "这是不明智的 \nThis is unwise",
    624: "不要陷入到情绪之中 \nDon't get caught up in emotions",
    625: "采纳智者的建议 \nAdopt the advice of the wise",
    626: "为了做出最好的决定，务必保持冷静 \nTo make the best decision, be sure to stay calm",
    627: "尝试一个更没把握的方法 \nTry a more uncertain method",
    628: "你必须马上行动 \nYou must act immediately",
    629: "接受一些改变 \nAccept some changes",
    630: "那可能已无法改变 \nThat may be unchangeable",
    631: "只做一次 \nDo it only once",
    632: "遵循智者的建议 \nFollow the advice of the wise",
    633: "你现在比以往任何时候都清楚 \nYou are clearer than ever before",
    634: "这不是很确定 \nThis is not very certain",
    635: "那将是一件乐事 \nThat will be a pleasure",
    636: "要知道选择太多或太少都很难 \nKnow that too many or too few choices are difficult",
    637: "那仍然无法预测 \nThat is still unpredictable",
    638: "有些障碍需要克服 \nSome obstacles need to be overcome",
    639: "最好的解决方法可能不太明显 \nThe best solution may not be obvious",
    640: "节省你的精力吧 \nSave your energy",
    641: "无论你做什么，结果依旧 \nNo matter what you do, the result remains the same",
    642: "遵循其他人的建议 \nFollow others' advice",
    643: "你终会搞清楚你想知道的一切 \nYou will eventually figure out everything you want to know",
    644: "看来还行 \nIt seems okay",
    645: "绝不 \nNever",
    646: "你可能会遭遇反对 \nYou may encounter opposition",
    647: "不要陷入你的情绪 \nDon't get caught up in your emotions",
    648: "最好的解决方法可能并不明显 \nThe best solution may not be obvious",
    649: "你可能不得不放弃其他一些东西 \nYou may have to give up some other things",
    650: "这肯定会使事情变得有趣 \nThis will definitely make things interesting",
    651: "遵循其他人的意见 \nFollow others' opinions",
    652: "慷慨大度些 \nBe more generous",
    653: "重新考虑下你的方法 \nReconsider your method",
    654: "把这看作一次机会 \nTreat this as an opportunity",
    655: "别再犹豫了 \nDon't hesitate anymore",
    656: "别难过，你是最棒的 \nDon't be sad, you are the best",
    657: "时间会证明一切 \nTime will prove everything",
    658: "需要一个相当大的努力 \nA considerable effort is needed",
    659: "从现在开始 一年也没有关系 \nIt doesn't matter if it takes a year from now",
    660: "实际一点吧 \nBe realistic",
    661: "合作将会是关键 \nCooperation will be the key",
    662: "考虑一下这个机会 \nConsider this opportunity",
    663: "早点去做 \nDo it early",
    664: "无需多问，尽力去做 \nNo need to ask more, just do your best",
    665: "别让压力打乱你的节奏 \nDon't let stress disrupt your rhythm",
    666: "也许会有好转 \nMaybe it will get better",
    667: "是时候做新的打算了 \nIt's time to make new plans",
    668: "不用怀疑了 \nNo need to doubt",
    669: "不要陷入你的感情 \nDon't get caught up in your feelings",
    670: "先完成其他事情 \nFinish other things first",
    671: "专注你眼下的生活 \nFocus on your current life",
    672: "遵循别人的引导 \nFollow others' guidance",
    673: "遵循专家的建议 \nFollow the advice of experts",
    674: "按照你的意愿 \nAccording to your will",
    675: "坚持终有回报 \nPersistence will eventually pay off",
    676: "也许是一段奇妙的旅程 \nMaybe it's a wonderful journey",
    677: "这是你不会忘记的 \nThis is something you won't forget",
    678: "这肯定会让事情变得有趣 \nThis will definitely make things interesting",
    679: "这是不确定的 \nThis is uncertain",
    680: "木已成舟 \nThe wood is already made into a boat (what's done is done)",
    681: "这可能很难，但你会发现它的价值 \nThis may be difficult, but you will find its value",
    682: "这将影响别人对你的看法 \nThis will affect how others see you",
    683: "这将是一种享受 \nThis will be a pleasure",
    684: "前路仍不可预测 \nThe future is still unpredictable",
    685: "它会让你付出代价 \nIt will cost you",
    686: " 现在就是绝佳的时机 \nNow is the perfect time",
    687: "请摆脱当前束缚 \nPlease break free from current constraints",
    688: "让它过去吧 \nLet it go",
    689: "注重细节 \nFocus on details",
    690: "为突发事件做好准备 \nPrepare for unexpected events",
    691: "重新考虑你的方法 \nReconsider your method",
    692: "得真正地努力一下 \nReally need to work hard",
    693: "重新考虑优先级 \nReconsider priorities",
    694: "尊重规则 \nRespect the rules",
    695: "寻找更多选择 \nLook for more options",
    696: "很快就会解决它 \nIt will be solved soon",
    697: "整个宇宙都会过来帮你 \nThe whole universe will come to help you",
    698: "需冒险一试 \nNeed to take a risk",
    699: "这会超出你的控制 \nThis will be beyond your control",
    700: "解决办法可能不太明显 \nThe solution may not be obvious",
    701: "机会不会很快再来 \nOpportunity won't come again soon",
    702: "情况将很快发生改变 \nThe situation will change soon",
    703: "结果会是好的 \nThe result will be good",
    704: "有充分的理由保持乐观 \nThere is sufficient reason to be optimistic",
    705: "会有障碍要克服 \nThere will be obstacles to overcome",
    706: "这是制定新计划的好时机 \nThis is a good time to make a new plan",
    707: "想做出最佳决策，需要保持冷静 \nTo make the best decision, you need to stay calm",
    708: "相信自己的直觉 \nTrust your intuition",
    709: "别忘记你的初心 \nDon't forget your original intention",
    710: "尝试一种不太可能的解决方案 \nTry an unlikely solution",
    711: "不宜在这个时候 \nNot suitable at this time",
    712: "无论如何你可以提升 \nYou can improve anyway",
    713: "你能以任何方式改变现状 \nYou can change the current situation in any way",
    714: "等一等 \nWait a minute",
    715: "一个正在到来的晴天 \nA coming sunny day",
    716: "注意你的节奏 \nPay attention to your rhythm",
    717: "不管你做什么，结果将会影响你 \nNo matter what you do, the result will affect you",
    718: "可以 \nYes",
    719: "是的，但不要勉强 \nYes, but don't force it",
    720: "你会发现自己无法妥协 \nYou will find that you can't compromise",
    721: "你知道现在比以前好 \nYou know it's better now than before",
    722: "你可能会放弃其他东西 \nYou may give up other things",
    723: "你现在必须行动 \nYou must act now",
    724: "你会发现一切你所需要知道的 \nYou will find everything you need to know",
    725: "岁月静好，长乐未央 \nThe years are peaceful and quiet, and happiness lasts forever",
    726: "你会庆幸你做了 \nYou will be glad you did it",
    727: "学会妥协 \nLearn to compromise",
    728: "您需要了解更多信息 \nYou need to know more information",
    729: "你需要考虑其他办法 \nYou need to consider other methods",
    730: "你需要主动出击 \nYou need to take the initiative",
    731: "糊涂一点更好 \nIt's better to be a little confused",
    732: "不必为你无法控制的事情而担心 \nDon't worry about things you can't control",
    733: "不要忘记微笑 \nDon't forget to smile",
    734: "你失去的某天会归还与你 \nWhat you lost will be returned to you one day",
    735: "你的状态很不对 \nYour state is very wrong",
    736: "你或许需要突破 \nYou may need a breakthrough",
    737: "你唯一能做的只有把握现在 \nThe only thing you can do is grasp the present",
    738: "学会珍惜 \nLearn to cherish",
    739: "调整心情，重新出发 \nAdjust your mood and start again",
    740: "请坚持不懈的努力 \nPlease make persistent efforts",
    741: "不合适 \nNot suitable",
    742: "换一个方向 \nChange direction",
    743: "放轻松，这很简单 \nTake it easy, it's simple",
    744: "也许会迟到 \nMay be late",
    745: "你的行动会改变现状 \nYour actions will change the current situation",
    746: "奇迹会降临 \nA miracle will come",
    747: "放手 \nLet go",
    748: "感恩，运气会越来越好 \nBe grateful, and luck will get better and better",
    749: "学会自我欣赏，你很棒 \nLearn to appreciate yourself, you are great",
    750: "复杂的事情简单做 \nSimplify complex things",
    751: "小题大做 \nMake a mountain out of a molehill",
    752: "学会保护自己 \nLearn to protect yourself",
    753: "给自己一个肯定 \nGive yourself an affirmation",
    754: "你的行动会使一切变得更好 \nYour actions will make everything better",
    755: "把握现在 \nGrasp the present",
    756: "会取得更好的结果 \nWill achieve better results",
    757: "一切从头开始 \nStart all over again",
    758: "下这一注稳赢 \nThis bet is a sure win",
    759: "做最重要的决定 \nMake the most important decision",
    760: "亏本买卖 \nA losing deal",
    761: "今朝有酒，今朝醉 \nDrink when you have wine today (enjoy the present)",
    762: "及时行乐 \nEnjoy pleasure in time",
    763: "以甜治甜，以丧治丧 \nTreat sweetness with sweetness, treat sorrow with sorrow",
    764: "你不是真心的在意 \nYou don't really care",
    765: "你不用最棒 \nYou don't have to be the best",
    766: "你会因为你做了而感到快乐 \nYou will be happy because you did it",
    767: "你很棒，自信起来吧 \nYou are great, be confident",
    768: "你心里已有答案 \nYou already have the answer in your heart",
    769: "停止 emo\nStop being emotional",
    770: "我们需要去打开窗 \nWe need to open the window",
    771: "糖吃多了会傻，苦一点没关系 \nEating too much sugar makes you silly, a little bitterness is okay",
    772: "自己选择的路，跪着也要走完 \nThe road you choose, you have to walk it even on your knees",
    773: "有一个重要的东西用来过渡 \nThere is an important thing for transition",
    774: "难分好坏 \nHard to distinguish good from bad",
    775: "高兴起来吧，你这么厉害 \nCheer up, you are so capable",
    776: "随波逐流未必是好事 \nGoing with the flow may not be a good thing",
    777: "随波逐流未必是坏事 \nGoing with the flow may not be a bad thing",
    778: "需要一腔孤勇 \nNeed a bold courage",
    779: "问问自己，为什么要这么干 \nAsk yourself why you want to do this",
    780: "见好就收 \nQuit while you're ahead",
    781: "试着去爱 \nTry to love",
    782: "答案就在你身边 \nThe answer is by your side",
    783: "珍惜身边人 \nCherish the people around you",
    784: "由于是必经的过程 \nBecause it's a necessary process",
    785: "令人期待的事情马上就要发生 \nSomething expected is about to happen",
    786: "每天做一点，将会大不相同 \nDo a little every day, and it will be very different",
    787: "主动一点，人生会大不相同 \nBe proactive, and life will be very different",
    788: "以后再说 \nTalk about it later",
    789: "会很棒的 \nIt will be great",
    790: "会很顺利 \nIt will go smoothly",
    791: "会感到庆幸 \nWill feel 庆幸",
    792: "会是完美的 \nIt will be perfect",
    793: "会有一个风光明媚的未来 \nWill have a bright future",
    794: "会是甜的 \nIt will be sweet",
    795: "你开心就好 \nAs long as you are happy",
    796: "你说了算 \nYou have the final say",
    797: "准备迎接意料之外的结果 \nPrepare for unexpected results",
    798: "出门会遇到贵人 \nYou will meet a noble person when you go out",
    799: "别指望所有人理解你 \nDon't expect everyone to understand you",
    800: "别灰心，人生总是起起落落的 \nDon't be discouraged, life always has ups and downs",
    801: "别要求太多 \nDon't ask for too much",
    802: "别辜负了自己就好 \nJust don't let yourself down",
    803: "千万不能失败 \nMust not fail",
    804: "另择吉日 \nChoose another auspicious day",
    805: "学会自我自愈 \nLearn to self-heal",
    806: "学会表达自己 \nLearn to express yourself",
    807: "尽人事，听天命 \nDo your best and let fate take its course",
    808: "带着你顽皮的好奇心去探索它 \nExplore it with your playful curiosity",
    809: "很多事会随着时间好起来的 \nMany things will get better with time",
    810: "时间会告诉你一切 \nTime will tell you everything",
    811: "眼光长远一点 \nTake a long-term view",
    812: "研究它，然后享受它 \nStudy it, then enjoy it",
    813: "跟随其他人的领导 \nFollow the leadership of others",
    814: "值不值得争取 \nIs it worth striving for",
    815: "这是必然的，不要抗拒 \nThis is inevitable, don't resist",
    816: "不要刻意隐藏 \nDon't deliberately hide",
    817: "停止伤悲 \nStop being sad",
    818: "不要刻意压抑 \nDon't deliberately suppress",
    819: "背不动就放下 \nPut it down if you can't carry it",
    820: "不要怕 \nDon't be afraid",
    821: "回家吧，家是永远的避风港 \nGo home, home is always a safe haven",
    822: "不要去忘记 \nDon't forget",
    823: "自信起来吧 \nBe confident",
    824: "接受那些消失的 \nAccept those that have disappeared",
    825: "到此为止 \nStop here",
    826: "时间有限 \nTime is limited",
    827: "慢下来 \nSlow down",
    828: "挥手道别 \nWave goodbye",
    829: "未来可期 \nThe future is promising",
    830: "平平安安 \nSafe and sound",
    831: "挥别错的 \nSay goodbye to the wrong one",
    832: "有一些重要的事必须去做 \nThere are some important things to do",
    833: "用平淡的心态去追求 \nPursue with a plain mind",
    834: "一切皆有可能 \nAnything is possible",
    835: "控制自己的情绪 \nControl your emotions",
    836: "一切顺其自然 \nLet everything take its course",
    837: "一场铺满鲜花的道路 \nA road covered with flowers",
    838: "暂且不要判断 \nDon't judge for the time being",
    839: "不要一成不变 \nDon't be rigid",
    840: "你祈求的一切顺利 \nEverything you pray for goes smoothly",
    841: "享受全心全意的付出 \nEnjoy wholehearted dedication",
    842: "站在了最重要的地方 \nStand in the most important place",
    843: "你会得到大多数的支持 \nYou will get most of the support",
    844: "十分好的预感 \nA very good premonition",
    845: "学会改变什么 \nLearn what to change",
    846: "最划算的交易 \nThe most cost-effective deal",
    847: "学会成长 \nLearn to grow",
    848: "最好的事情正要发生 \nThe best thing is about to happen",
    849: "没有什么是对的 \nNothing is right",
    850: "必须努力奔跑起来 \nMust run hard",
    851: "会有人陪着你 \nThere will be someone with you",
    852: "站起来去战斗 \nStand up and fight",
    853: "出发 \nSet off",
    854: "不要给人添麻烦 \nDon't trouble others",
    855: "有人浪费了你的时间 \nSomeone wasted your time",
    856: "最后什么都没改变 \nIn the end, nothing changed",
    857: "找回自己 \nFind yourself",
    858: "你会得到重生 \nYou will be reborn",
    859: "需要直面残酷 \nNeed to face cruelty directly",
    860: "你大概会受点伤 \nYou will probably get a little hurt",
    861: "烦恼快要消失了 \nTroubles are about to disappear",
    862: "并不会让你高兴 \nIt won't make you happy",
    863: "没什么放不下 \nThere's nothing you can't let go of",
    864: "伤口很快会愈合 \nThe wound will heal soon",
    865: "悄悄躲开 \nSneak away",
    866: "完美的 \nPerfect",
    867: "不要做出任何决定 \nDon't make any decisions",
    868: "浪费光阴 \nWaste time",
    869: "停止向前 \nStop moving forward",
    870: "再也不要见 \nNever see each other again",
    871: "不会让你痛苦的 \nIt won't make you painful",
    872: "试着慷慨一点 \nTry to be more generous",
    873: "这是不能犹豫的事 \nThis is something you can't hesitate about",
    874: "试着安静一会 \nTry to be quiet for a while",
    875: "戒掉过分的急躁 \nQuit excessive impatience",
    876: "不要隐藏起来 \nDon't hide",
    877: "你好像舍不得 \nYou seem reluctant",
    878: "有点儿心疼 \nA little distressed",
    879: "车到山前必有路 \nWhen you get to the mountain, there will be a road",
    880: "你有必要傻一点 \nYou need to be a little silly",
    881: "你会忘记它 \nYou will forget it",
    882: "只是一场梦 \nIt's just a dream",
    883: "你要勇敢地离开 \nYou have to leave bravely",
    884: "尽你最大的努力 \nDo your best",
    885: "去忘记 \nTo forget",
    886: "大家好像都不认同 \nEveryone seems to disagree",
    887: "认真起来 \nGet serious",
    888: "值得去做的事 \nSomething worth doing",
    889: "转个身忘记吧 \nTurn around and forget",
    890: "这绝对是个好主意 \nThis is definitely a good idea",
    891: "你很幸运 \nYou are lucky",
    892: "机会就在眼前 \nOpportunity is right in front of you",
    893: "不如忘掉这个问题 \nIt's better to forget this problem",
    894: "专注一点 \nFocus a little",
    895: "殊途同归 \nDifferent roads lead to the same destination",
    896: "背道而驰 \nGo against the direction",
    897: "吃点东西，冷静一下 \nEat something and calm down",
    898: "这大概会让你哭泣 \nThis will probably make you cry",
    899: "既往不恋 \nDon't love the past",
    900: "捍卫它 \nDefend it",
    901: "不必耿耿于怀 \nDon't hold a grudge",
    902: "放在心里吧，这样比较好点 \nKeep it in your heart, it's better this way",
    903: "不用伪装到面目全非 \nDon't pretend to be unrecognizable",
    904: "别压抑自己的天性 \nDon't suppress your nature",
    905: "一个人安安静静呆一会儿 \nStay quiet alone for a while",
    906: "不要去想走多远 \nDon't think about how far you will go",
    907: "大哭一场会好受一点 \nCrying a lot will make you feel better",
    908: "总会慢慢淡去的 \nIt will fade away slowly",
    909: "明天就会有新鲜事发生 \nSomething new will happen tomorrow",
    910: "这种事情要靠缘分 \nThis kind of thing depends on fate",
    911: "这是起跑线 \nThis is the starting line",
    912: "没事，有我在 \nIt's okay, I'm here",
    913: " 不要把所有表情都写在脸上 \nDon't show all your expressions on your face",
    914: "别人会对你苦笑 \nOthers will give you a bitter smile",
    915: "好像会很累 \nIt seems like it will be very tiring",
    916: "你需要的只是勇气 \nAll you need is courage",
    917: "不甘心的话，就努力争取吧 \nIf you're not reconciled, work hard to fight for it",
    918: "无条件的付出 \nUnconditional dedication",
    919: "试着更快一些 \nTry to be faster",
    920: "不能永远一层不变 \nCan't stay the same forever",
    921: "会有一些困难 \nThere will be some difficulties",
    922: "等待下一个故事的发生 \nWait for the next story to happen",
    923: "试着面对自己的真实想法 \nTry to face your true thoughts",
    924: "愿意并且相信 \nBe willing and believe",
    925: "将要奔赴一场未知的旅程 \nAbout to embark on an unknown journey",
    926: "隐忍 \nEndure patiently",
    927: "不必要的退让 \nUnnecessary compromise",
    928: "这大概会让你有点寂寞 \nThis will probably make you a little lonely",
    929: "不要轻易去相信 \nDon't easily believe",
    930: "可能会很累 \nMay be very tiring",
    931: "会让周围的人感到温暖 \nWill make the people around feel warm",
    932: "大概要多想一会 \nProbably need to think a little more",
    933: "值得肯定 \nWorth affirming",
    934: "注意一下周围 \nPay attention to the surroundings",
    935: "看见的都不是真的 \nWhat you see is not real",
    936: "看向未来 \nLook to the future",
    937: "未来会变得特别繁忙 \nThe future will become very busy",
    938: "这简直太有趣了 \nThis is simply too interesting",
    939: "胜券在握 \nHave victory in hand",
    940: "突如其来的幸福 \nSudden happiness",
    941: "特别的见解 \nSpecial insight",
    942: "值得喝一杯 \nWorth having a drink",
    943: "并不确定真伪 \nNot sure about the authenticity",
    944: "保持你的好奇心，去挖掘真相 \nKeep your curiosity and dig out the truth",
    945: "谁说得准呢，先观望着 \nWho can tell? Just wait and see first",
    946: "天上要掉馅饼了 \nPie is going to fall from the sky (something good happens unexpectedly)",
    947: "还有另一种情况 \nThere is another situation",
    948: "别让它影响到你 \nDon't let it affect you",
    949: "时机不对 \nThe timing is wrong",
    950: "照你想的那样去做 \nDo as you think",
    951: "但行好事，莫问前程 \nJust do good deeds, don't ask about the future",
    952: "迷途漫漫，终有一归 \nThe lost journey is long, but there will eventually be a destination",
    953: "抛弃首选方案 \nAbandon the preferred plan",
    954: "走容易走的路 \nTake the easy road",
    955: "最佳方案不一定可行 \nThe best plan may not be feasible",
    956: "借助他人的经验 \nMake use of others' experience",
    957: "再多考虑 \nThink more",
    958: "机会稍纵即逝 \nOpportunity is fleeting",
    959: "你就是答案 \nYou are the answer",
    960: "培养一项新爱好 \nDevelop a new hobby",
    961: "观察形势 \nObserve the situation",
    962: "休息，休息一会 \nRest, take a break",
    963: "这是你最后的机会 \nThis is your last chance",
    964: "并不明智 \nNot wise",
    965: "保持头脑清醒 \nKeep a clear mind",
    966: "保存你的实力 \nPreserve your strength",
    967: "不确定的因素有点多 \nThere are a bit too many uncertain factors",
    968: "结果不错 \nThe result is good",
    969: "等待更好的 \nWait for something better",
    970: "制定计划 \nMake a plan",
    971: "很麻烦 \nVery troublesome",
    972: "克服困难 \nOvercome difficulties",
    973: "一年后就不那么重要了 \nIt won't be that important in a year",
    974: "去行动 \nTake action",
    975: "寻找一个指路人 \nFind a guide",
    976: "能让你快乐的那个决定 \nThe decision that can make you happy",
    977: "着眼未来 \nFocus on the future",
    978: "不要等了 \nDon't wait",
    979: "不要被情绪左右 \nDon't be swayed by emotions",
    980: "不要做得太过分 \nDon't go too far",
    981: "改变自己 \nChange yourself",
    982: "这是一个机会 \nThis is an opportunity",
    983: "问自己什么事最重要的 \nAsk yourself what is the most important thing",
    984: "不要忧虑 \nDon't worry",
    985: "你必须弥补这个缺点 \nYou must make up for this shortcoming",
    986: "忽略了一件显而易见的事 \nOverlooked an obvious thing",
    987: "别太赶了 \nDon't be in such a hurry",
    988: "还有别的选择 \nThere are other choices",
    989: "不好忽视自己的力量 \nIt's not good to ignore your own strength",
    990: "尽在掌握之中 \nAll under control",
    991: "无论怎样天塌不下来 \nNo matter what, the sky won't fall",
    992: "这件事会给你带来极大的乐趣 \nThis matter will bring you great joy",
    993: "无需纠结 \nNo need to be tangled",
    994: "老天也许在给你准备惊喜 \nGod may be preparing a surprise for you",
    995: "是好的 \nIt's good",
    996: "这是最佳选择之一 \nThis is one of the best choices",
    997: "没有更好的选择 \nThere is no better choice",
    998: "铸造自己的辉煌 \nCreate your own glory",
    999: "别在这上面下赌注 \nDon't bet on this"
};

// 获取页面元素
const pageInput = document.getElementById('pageInput');
const answerDisplay = document.getElementById('answerDisplay');
const answerText = document.getElementById('answer');
const getAnswerButton = document.getElementById('getAnswer');
const randomButton = document.getElementById('getRandomAnswer');
const tryAgainButton = document.getElementById('tryAgain');
const page3Image = document.getElementById('page3Image');

// 输入框限制
pageInput.addEventListener('input', (e) => {
    let value = e.target.value.replace(/[^0-9]/g, '');
    if (parseInt(value) > 999) value = '999';
    e.target.value = value;
});

// 文本分行函数
function splitTextIntoLines(text, charsPerLine) {
    const lines = [];
    let currentLine = '';
    
    for (let char of text) {
        if (currentLine.length >= charsPerLine) {
            lines.push(currentLine);
            currentLine = '';
        }
        currentLine += char;
    }
    if (currentLine) {
        lines.push(currentLine);
    }
    return lines;
}

// 显示答案的函数
function displayAnswerText(text) {
    // 分割中英文答案
    const [chinese, english] = text.split('\n');
    
    // 将中文按10个字符分行
    const chineseLines = splitTextIntoLines(chinese, 10);
    
    // 生成HTML，确保每行正好10个字符
    const chineseHtml = chineseLines
        .map(line => {
            // 如果行长度不足10个字符，在两边添加空格使其居中
            const paddingNeeded = 10 - line.length;
            const leftPadding = Math.floor(paddingNeeded / 2);
            const rightPadding = paddingNeeded - leftPadding;
            const paddedLine = '　'.repeat(leftPadding) + line + '　'.repeat(rightPadding);
            return `<div class="answer-line">${paddedLine}</div>`;
        })
        .join('');
    
    // 更新h3和答案文本
    document.querySelector('#answerDisplay h3').style.display = 'block';
    const h3Text = document.querySelector('#answerDisplay h3').textContent;
    const h3Lines = splitTextIntoLines(h3Text, 10);
    document.querySelector('#answerDisplay h3').innerHTML = h3Lines
        .map(line => `<div class="h3-line">${line}</div>`)
        .join('');
    
    answerText.innerHTML = `
        <div class="answer-chinese">${chineseHtml}</div>
        <div class="answer-english">${english}</div>
    `;
}

// 获取答案的逻辑
getAnswerButton.addEventListener('click', () => {
    if (!pageInput.value) {
        alert('请输入页数！');
        return;
    }

    let pageNum = parseInt(pageInput.value);
    if (pageNum < 1) pageNum = pageInput.value = 1;
    if (pageNum > 999) pageNum = pageInput.value = 999;

    // 显示思考动画
    getAnswerButton.disabled = true;
    getAnswerButton.textContent = '思考中...';
    
    setTimeout(() => {
        // 计算答案
        const answerIndex = pageNum % Object.keys(answers).length || Object.keys(answers).length;
        
        // 显示答案
        displayAnswerText(answers[answerIndex]);
        answerDisplay.classList.remove('hidden');
        
        // 隐藏所有其他元素
        document.querySelector('#answerDisplay h3').style.display = 'none';
        document.querySelector('.container header').style.display = 'none';
        document.querySelector('.instructions').style.display = 'none';
        document.querySelector('.input-group').style.display = 'none';
        randomButton.style.display = 'none';
        
        // 显示再尝试按钮和装饰图片
        tryAgainButton.style.display = 'block';
        page3Image.classList.remove('hidden');
        page3Image.classList.add('show');
        
        // 重置按钮状态
        getAnswerButton.disabled = false;
        getAnswerButton.textContent = '获取答案';
    }, 1500);
});

// 随机答案按钮逻辑
randomButton.addEventListener('click', () => {
    // 显示思考动画
    randomButton.disabled = true;
    randomButton.textContent = '思考中...';
    
    setTimeout(() => {
        // 随机选择答案
        const randomIndex = Math.floor(Math.random() * Object.keys(answers).length) + 1;
        
        // 显示答案
        displayAnswerText(answers[randomIndex]);
        answerDisplay.classList.remove('hidden');
        
        // 隐藏其他元素
        document.querySelector('#answerDisplay h3').style.display = 'none';
        document.querySelector('.container header').style.display = 'none';
        document.querySelector('.instructions').style.display = 'none';
        document.querySelector('.input-group').style.display = 'none';
        randomButton.style.display = 'none';
        
        // 显示再尝试按钮和装饰图片
        tryAgainButton.style.display = 'block';
        page3Image.classList.remove('hidden');
        page3Image.classList.add('show');

        // 重置按钮状态
        randomButton.disabled = false;
        randomButton.textContent = '直接获取答案';
    }, 1500);
});

// 重试按钮逻辑
tryAgainButton.addEventListener('click', () => {
    // 重置输入和显示
    pageInput.value = '';
    answerDisplay.classList.add('hidden');
    
    // 隐藏第3页图片
    page3Image.classList.add('hidden');
    page3Image.classList.remove('show');
    
    // 恢复所有元素显示
    document.querySelector('#answerDisplay h3').style.display = 'block';
    document.querySelector('.container header').style.display = 'block';
    document.querySelector('.instructions').style.display = 'block';
    document.querySelector('.input-group').style.display = 'flex';
    randomButton.style.display = 'block';
}); 
